spring:
  application:
    name: greeting-service
# noinspection undefined
greeting-service:
  greeting: "Application de producao parceiro"
  default-value: "Tu é burro"
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

